site:
  title: TME Tigers POC
  url: https://tme-tigers.github.io/demo/docs-site
  start_page: index.adoc
content:
  sources:
  - url: https://github.com/pandeybk/antora-project-a.git
    branches: HEAD
    edit_url: false
  - url: https://github.com/pandeybk/antora-project-b.git
    branches: [main, v2.0, v1.0]
    start_path: docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
